version: '3'

tasks:
  # Default entry point (cmd/app)
  dev:app:
    desc: Run app with hot reload (Air)
    cmds:
      - air -c .air.app.toml

  build:app:
    desc: Build app binary
    cmds:
      - go build -o bin/app ./cmd/app

  run:app:
    desc: Run app binary
    cmds:
      - ./bin/app

  test:
    desc: Run tests
    cmds:
      - go test ./... -v

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - go test ./... -coverprofile=coverage.out
      - go tool cover -html=coverage.out -o coverage.html

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - goimports -w .

  tidy:
    desc: Tidy dependencies
    cmds:
      - go mod tidy

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - rm -f coverage.out coverage.html

  # VPKG commands
  vpkg:add:
    desc: Add a VPKG package
    cmds:
      - vandor vpkg add {{.CLI_ARGS}}

  vpkg:list:
    desc: List installed VPKG packages
    cmds:
      - vandor vpkg list

  vpkg:remove:
    desc: Remove a VPKG package
    cmds:
      - vandor vpkg remove {{.CLI_ARGS}}

  # Domain commands
  domain:add:
    desc: Add a new domain
    cmds:
      - vandor add domain {{.CLI_ARGS}}

  # Code generation
  sync:
    desc: Regenerate all code
    cmds:
      - vandor sync all
